/* Generated By:JJTree: Do not edit this line. ASTAtomicNumber.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace NCDK.Smiles.SMARTS.Parser
{
    public
    class ASTAtomicNumber : SimpleNode
    {
        public ASTAtomicNumber(int id)
          : base(id)
        {
        }

        public ASTAtomicNumber(SMARTSParser p, int id)
          : base(p, id)
        {
        }

        /// <summary>
        /// the atomic number.
        /// </summary>
        public int Number { get; set; }

        /// <summary>Accept the visitor. </summary>
        public override object JjtAccept(SMARTSParserVisitor visitor, object data)
        {
            return visitor.Visit(this, data);
        }
    }
}
