/* Generated By:JJTree: Do not edit this line. ASTGroup.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
using NCDK.Isomorphisms.Matchers.SMARTS;

namespace NCDK.Smiles.SMARTS.Parser
{
    internal class ASTGroup : SimpleNode
    {
        public ReactionRoles Role { get; set; } = ReactionRoles.Any;

        public ASTGroup(int id)
          : base(id)
        {
        }

        public ASTGroup(SMARTSParser p, int id)
          : base(p, id)
        {
        }

        /// <summary>Accept the visitor. </summary>
        public override object JjtAccept(ISMARTSParserVisitor visitor, object data)
        {
            return visitor.Visit(this, data);
        }
    }
}
