/* Generated By:JavaCC: Do not edit this line. SMARTSParserTreeConstants.java Version 5.0 */
namespace NCDK.Smiles.SMARTS.Parser
{
    public static class SMARTSParserTreeConstants
    {
        public const int JJTSTART = 0;
        public const int JJTREACTION = 1;
        public const int JJTGROUP = 2;
        public const int JJTSMARTS = 3;
        public const int JJTATOM = 4;
        public const int JJTLOWANDBOND = 5;
        public const int JJTORBOND = 6;
        public const int JJTEXPLICITHIGHANDBOND = 7;
        public const int JJTIMPLICITHIGHANDBOND = 8;
        public const int JJTNOTBOND = 9;
        public const int JJTSIMPLEBOND = 10;
        public const int JJTEXPLICITATOM = 11;
        public const int JJTLOWANDEXPRESSION = 12;
        public const int JJTOREXPRESSION = 13;
        public const int JJTEXPLICITHIGHANDEXPRESSION = 14;
        public const int JJTIMPLICITHIGHANDEXPRESSION = 15;
        public const int JJTNOTEXPRESSION = 16;
        public const int JJTRECURSIVESMARTSEXPRESSION = 17;
        public const int JJTVOID = 18;
        public const int JJTTOTALHCOUNT = 19;
        public const int JJTIMPLICITHCOUNT = 20;
        public const int JJTEXPLICITCONNECTIVITY = 21;
        public const int JJTATOMICNUMBER = 22;
        public const int JJTHYBRDIZATIONNUMBER = 23;
        public const int JJTCHARGE = 24;
        public const int JJTRINGCONNECTIVITY = 25;
        public const int JJTPERIODICGROUPNUMBER = 26;
        public const int JJTTOTALCONNECTIVITY = 27;
        public const int JJTVALENCE = 28;
        public const int JJTRINGMEMBERSHIP = 29;
        public const int JJTSMALLESTRINGSIZE = 30;
        public const int JJTALIPHATIC = 31;
        public const int JJTNONCHHEAVYATOM = 32;
        public const int JJTAROMATIC = 33;
        public const int JJTANYATOM = 34;
        public const int JJTATOMICMASS = 35;
        public const int JJTRINGIDENTIFIER = 36;
        public const int JJTCHIRALITY = 37;
        public const int JJTELEMENT = 38;


        public static readonly string[] jjtNodeName = new string[] {
            "Start",
            "Reaction",
            "Group",
            "Smarts",
            "Atom",
            "LowAndBond",
            "OrBond",
            "ExplicitHighAndBond",
            "ImplicitHighAndBond",
            "NotBond",
            "SimpleBond",
            "ExplicitAtom",
            "LowAndExpression",
            "OrExpression",
            "ExplicitHighAndExpression",
            "ImplicitHighAndExpression",
            "NotExpression",
            "RecursiveSmartsExpression",
            "void",
            "TotalHCount",
            "ImplicitHCount",
            "ExplicitConnectivity",
            "AtomicNumber",
            "HybrdizationNumber",
            "Charge",
            "RingConnectivity",
            "PeriodicGroupNumber",
            "TotalConnectivity",
            "Valence",
            "RingMembership",
            "SmallestRingSize",
            "Aliphatic",
            "NonCHHeavyAtom",
            "Aromatic",
            "AnyAtom",
            "AtomicMass",
            "RingIdentifier",
            "Chirality",
            "Element",
        };
    }
}
